library(anytime)
library(dplyr)
library(keyring)
library(here)
library(httr)
library(jsonlite)
library(readr)
library(tidyr)


# Function to get changes from Weblate API

## Specific actions can be defined by action number, see `actions.csv` for a
## look-up table generated by `weblate_actions.R`.
## The arguments `date_after` and `date_before` are not inclusive.

get_changes <- function(key,
                        action = NULL,
                        date_after = NULL,
                        date_before = NULL,
                        verbose = TRUE){
    # create URL
    url <- "https://translate.rx.studio/api/changes/?page=1"
    if (!is.null(action))
        url <- paste0(url, "&action=", action)
    if (!is.null(date_after))
        url <- paste0(url, "&timestamp_after=", iso8601(anytime(date_after) + days(1)))
    if (!is.null(date_before))
        url <- paste0(url, "&timestamp_before=", iso8601(anytime(date_before)))

    # get first page of changes (returns up to 50 at a time)
    if (verbose) message("Getting changes for action ", action)
    response <- GET(url, add_headers(Authorization = paste("Token", key)))
    content <- fromJSON(rawToChar(response$content))
    changes_first <- content$results

    # get remaining changes, if any
    n <- content$count %/% 50
    changes_remaining <- vector(mode = "list", length = n + 1)
    for (i in seq_len(n)){
        if (verbose) message("...page ", i + 1, " out of ", n + 1)
        response <- GET(content$`next`,
                        add_headers(Authorization = paste("Token", key)))
        content <- fromJSON(rawToChar(response$content))
        changes_remaining[[i]] <- content$results
    }

    # combine and return
    do.call("rbind", c(list(changes_first), changes_remaining))
}

# Get personal API key

## key_set("Weblate") # get personal API from account settings in Weblate
key <- key_get("Weblate")

# Get data for analysis

all_changes <- get_changes(key, date_before = "2023-09-02")
write_csv(all_changes,
          here("r_project_sprint", "all_changes_before_2023-09-01.csv"))

tmp <- get_changes(key, action = 36,
                   date_after = "2023-08-29", date_before = "2023-09-02")
